/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.edifree.edifact.main.all.custom_object;

import org.edifree.edifact.main.all.exception.EdifactLibraryException;

/**
 *
 * @author Rafal Paszkowski
 */
public enum EdifactType {
    APERAK,AUTACK,AUTHOR,BALANC,BANSTA,BAPLIE,BAPLTE,BERMAN,BMISRM,BOPBNK,BOPCUS,BOPDIR,BOPINF,BUSCRD,CALINF,CASINT,CASRES,CHACCO,CLASET,CNTCND,COACSU,COARRI,CODECO,CODENO,COEDOR,COHAOR,COLREQ,COMDIS,CONAPW,CONDPV,CONDRA,CONDRO,CONEST,CONITT,CONPVA,CONQVA,CONRPW,CONTEN,CONWQD,COPARN,COPAYM,COPINO,COPRAR,COREOR,COSTCO,COSTOR,CREADV,CREEXT,CREMUL,CUSCAR,CUSDEC,CUSEXP,CUSPED,CUSREP,CUSRES,DAPLOS,DEBADV,DEBMUL,DEBREC,DELFOR,DELJIT,DESADV,DESTIM,DGRECA,DIRDEB,DIRDEF,DMRDEF,DMSTAT,DOCADV,DOCAMA,DOCAMI,DOCAMR,DOCAPP,DOCARE,DOCINF,ENTREC,FINCAN,FINPAY,FINSTA,GENRAL,GESMES,GOVCBR,HANMOV,ICASRP,ICSOLI,IFCSUM,IFTCCA,IFTDGN,IFTFCC,IFTIAG,IFTICL,IFTMAN,IFTMBC,IFTMBF,IFTMBP,IFTMCA,IFTMCS,IFTMFR,IFTMIN,IFTRIN,IFTSAI,IFTSTA,IFTSTQ,IMPDEF,INFCON,INFENT,INSDES,INSPRE,INSREQ,INSRPT,INVOIC,INVRPT,IPPOAD,IPPOMO,ISENDS,ITRRPT,JAPRES,JINFDE,JOBAPP,JOBCON,JOBMOD,JOBOFF,JUPREQ,LEDGER,LREACT,LRECLM,MEDPID,MEDPRE,MEDREQ,MEDRPT,MEDRUC,MEQPOS,MOVINS,MSCONS,ORDCHG,ORDERS,ORDRSP,OSTENQ,OSTRPT,PARTIN,PAXLST,PAYDUC,PAYEXT,PAYMUL,PAYORD,PRICAT,PRIHIS,PROCST,PRODAT,PRODEX,PROINQ,PROSRV,PROTAP,PRPAID,QALITY,QUOTES,RDRMES,REBORD,RECADV,RECALC,RECECO,RECLAM,RECORD,REGENT,RELIST,REMADV,REPREM,REQDOC,REQOTE,RESETT,RESMSG,RETACC,RETANN,RETINS,RPCALL,SAFHAZ,SANCRT,SLSFCT,SLSRPT,SOCADE,SSIMOD,SSRECH,SSREGW,STATAC,STLRPT,SUPCOT,SUPMAN,SUPRES,TANSTA,TAXCON,TPFREP,UTILMD,UTILTS,VATDEC,VERMAS,VESDEP,WASDIS,WKGRDC,WKGRRE;

    EdifactType() {
    }

    public static EdifactType create(String edifactType) throws EdifactLibraryException {
        for(EdifactType e:EdifactType.values()){
            if(e.name().trim().equalsIgnoreCase(edifactType)){
                return e;
            }
        }
        //log. TODO !!!!
        throw new EdifactLibraryException("Can not create edifact type. No text found:"+edifactType);
    }
}
